[workspace]

members = [
    "crates/uiautomation",
    "crates/uiautomation_derive",
    "samples/uia_print",
    "samples/uia_cached_print",
    "samples/uia_notepad",
    "samples/uia_varaint",
    "samples/win_update", 
    "tests/core_test", "samples/uia_event_handler",
]

resolver = "2"
